function plainAddPlaceholder remove metadata of pdf (#36)
vbuch/node-signpdf pull request #112
Opened 2020-12-21 14:58 UTC by cdebevotte

Fix for: function plainAddPlaceholder remove metadata of pdf (#36)

2020-12-22 07:07 UTC, vbuch requested changes
Just make sure coverage remains at 100% and this gets merged.
Thank you!

2020-12-22 07:07 UTC, vbuch commented on src/helpers/plainAddPlaceholder/createBufferTrailer.js
> -        Buffer.from('/Info 15 0 R\n'),
Wow! That's a nice hardcoded bit :-)

2020-12-22 08:46 UTC, cdebevotte commented
This is my first time doing a PR, I'm not very used to it :-)

2020-12-23 09:49 UTC, vbuch approved these changes

2020-12-23 09:56 UTC, merged

2020-12-23 09:57 UTC, vbuch commented
It's in develop. Will try to get it released these days. Thank you for the contribution @cdebevotte